version: "3.8"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ${MARIADB_VOLUME}
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ${WORDPRESS_VOLUME}

services:
  mariadb:
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: mariadb
    image: mariadb:minjungk
    build: ./requirements/mariadb
    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 30s
      timeout: 3s
      retries: 3

  wordpress:
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    env_file:
      - .env
    environment:
      - COMPOSE_PROFILES
      - HTTP_HOST=${DOMAIN_NAME}
    restart: on-failure:3
    container_name: wordpress
    image: wordpress:minjungk
    build: ./requirements/wordpress
    healthcheck:
      test: ['CMD-SHELL', 'cgi-fcgi -bind -connect localhost:9000']
      interval: 30s
      timeout: 3s
      retries: 3

  nginx:
    depends_on:
      - wordpress
    hostname: ${DOMAIN_NAME}
    expose:
      - "443"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: nginx
    image: nginx:minjungk
    build: ./requirements/nginx
    healthcheck:
      test: ['CMD-SHELL', 'curl -k https://localhost:443']
      interval: 30s
      timeout: 3s
      retries: 3
    secrets:
      - server.pem
      - server.key

  redis:
    profiles:
      - bonus
    expose:
      - "6379"
    networks:
      - inception
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: redis
    image: redis:minjungk
    build: ./requirements/bonus/redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 30s
      timeout: 3s
      retries: 3

  ftp:
    profiles:
      - bonus
    expose:
      - "21"
      - "21100-21110"
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    volumes:
      - wordpress:/home/${FTP_USER}
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: ftp
    image: ftp:minjungk
    build:
      context: ./requirements/bonus/ftp
      args:
        - FTP_USER=${FTP_USER}
    healthcheck:
      test: ['CMD-SHELL', 'nc -zv localhost 21']
      interval: 30s
      timeout: 3s
      retries: 3

  web:
    profiles:
      - bonus
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - inception
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: web
    image: web:minjungk
    build: ./requirements/bonus/web
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:80']
      interval: 30s
      timeout: 3s
      retries: 3

  adminer:
    profiles:
      - bonus
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - inception
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: adminer
    image: adminer:minjungk
    build: ./requirements/bonus/adminer
    healthcheck:
      test: ['CMD-SHELL', 'nc -zv localhost 8080']
      interval: 30s
      timeout: 3s
      retries: 3

  exim:
    profiles:
      - bonus
    expose:
      - "25"
    ports:
      - "25:25"
    networks:
      - inception
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: exim
    image: exim:minjungk
    build: ./requirements/bonus/exim
    healthcheck:
      test: ['CMD-SHELL', 'nc -zv localhost 25']
      interval: 30s
      timeout: 3s
      retries: 3

secrets:
  server.pem:
    file: ${CERTS_}/${DOMAIN_NAME}.pem
  server.key:
    file: ${CERTS_}/${DOMAIN_NAME}.key
