version: "3.8"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ${MARIADB_VOLUME}
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: "bind"
      type: "none"
      device: ${WORDPRESS_VOLUME}

services:
  mariadb:
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: mariadb
    image: mariadb:minjungk
    build: ./requirements/mariadb
    healthcheck:
      test: ['CMD-SHELL', 'mariadb-admin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 3s
      retries: 3

  wordpress:
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    env_file:
      - .env
    environment:
      - COMPOSE_PROFILES
      - HTTP_HOST=${DOMAIN_NAME}
    restart: on-failure:3
    container_name: wordpress
    image: wordpress:minjungk
    build: ./requirements/wordpress
    healthcheck:
      test: ['CMD-SHELL', 'cgi-fcgi -bind -connect localhost:9000']
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    depends_on:
      - wordpress
    hostname: ${DOMAIN_NAME}
    expose:
      - "443"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: nginx
    image: nginx:minjungk
    build: ./requirements/nginx
    secrets:
      - server.pem
      - server.key

  redis:
    profiles:
      - bonus
    expose:
      - "6379"
    networks:
      - inception
    env_file:
      - .env
    init: true
    restart: on-failure:3
    container_name: redis
    image: redis:minjungk
    build: ./requirements/bonus/redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      timeout: 3s
      retries: 3

secrets:
  server.pem:
    file: ${CERTS_}/${DOMAIN_NAME}.pem
  server.key:
    file: ${CERTS_}/${DOMAIN_NAME}.key
